import {
  Accordion,
  Button,
  Card,
  Checkbox,
  Datepicker,
  Form,
  HorizontalStack,
  Input,
  Pagination,
  Select,
  Table,
  Textarea,
  VerticalStack,
} from "@/components/layout";

export const COMPONENTS_MAP = {
  button: Button,
  card: Card,
  checkbox: Checkbox,
  datepicker: Datepicker,
  form: Form,
  h_stack: HorizontalStack,
  input: Input,
  select: Select,
  textarea: Textarea,
  v_stack: VerticalStack,
  table: Table,
  accordion: Accordion,
  pagination: Pagination,
};
